name: Generate Pacman

on:
  schedule:
    # Runs once a day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Pacman animation
      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: Mohitscodiclab
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      # Push the generated files back to your repo
      - name: Push Pacman to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
